import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jonathan Galli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.grid}>
          <main className={styles.main}>
            <div className={styles.grid}>

              <div className={styles.profilePicture}/>
              <h1 className={styles.title}>
                Jonathan Galli
              </h1>
            </div>

            <section>
              <p className={styles.description}>
                Hi, I'm a full-stack developer, graduated in IT!
                <br />
                Here you'll see my development skills and portfolio.
                <br />
                <br />
                I'm a musician also, check out my music projects <a className={styles.a} href="music">clicking here</a>!
              </p>
            </section>
            
            <h2>About me</h2>
            <p className={styles.description}>
              Since 2019, I started studying and realized a passion about learning programmation. As I don't like to waste time,
              I became a fast learner and self-taught.
              <br />
              <span style={{fontStyle:"italic"}}>I'm passionate about learning, making friends and beating challenges.</span>
              <br />
              I already was the project manager of some projects and this was how I learned working in a team and leadership.
            </p>
            
          </main>

          <div className={styles.skillGrid}>
            <h2>Main Skills</h2>
            <div className={styles.grid}>
              <Card name="Web" description="NextJS, React, Node, JavaScript, TypeScript" />
              <Card name="Mobile" description="Android Studio, Java" />
              <Card name="Python" description="Pandas, Numpy, Docx, Tkinter, Pillow, Pyautogui, Pynput, etc" />
              <Card name="Games" description="Unity, C#" />
            </div>
          </div>
        </div>
      </div>

      <div className={styles.portfolio}>
        <h1>Portfolio</h1>
          <div className={styles.grid}>
            <Card href='/' name='Personal Website' description="This website, made with NextJS and React" />
            <Card href='spellapi' name='SpellAPI' description="An Unity's API for creation of spells in games" />
          </div>
      </div>

      <div className="container">
        <h2 style={{marginTop:'24px'}}>Other skills</h2>
        <ul>

            <li>Rest</li>
            <li>Angular</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>Lua</li>
            <li>Laravel</li>
            <li>Roblox Studio</li>
        </ul>
      </div>

      <footer className={styles.footer}>
        <span>
          Email jonathanribeirogalli@hotmail.com
        </span>
        <span>
          Instagram <a href="https://instagram.com/jonathanribeirogalli">@jonathanribeirogalli</a>
        </span>
        <span>
          LinkedIn <a href="https://www.linkedin.com/in/jonathan-galli/">Jonathan Galli</a>
        </span>
        <span>
          GitHub <a href="https://github.com/JhowBR">@JhowBR</a>
        </span>
        <span>
          Phone +55 (45) 98835-9119
        </span>
      </footer>
    </div>
  )
}

export default Home
